version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: cloudreach/sceptre-circleci
    docker:
      - image: cimg/base:2021.03

jobs:
  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  deploy-latest-dockerhub:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load Docker image archive
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

  deploy-dockerhub-tagged:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Tagged Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build-docker-image:
          context: sceptre-core
          filters:
            tags:
              only: /.*/

      - deploy-latest-dockerhub:
          context: sceptre-core
          requires:
            - build-docker-image
          filters:
            branches:
              only: master

      - deploy-dockerhub-tagged:
          context: sceptre-core
          requires:
            - build-docker-image
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
