version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: sceptreorg/sceptre-circleci
    docker:
      - image: cimg/base:2022.05

jobs:
  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  deploy-latest-dockerhub:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Load Docker image archive
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

  deploy-dockerhub-tagged:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Tagged Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  pre-merge:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only: /^pull\/.*/
  post-merge:
    jobs:
      - build-docker-image:
          filters:
            branches:
              ignore: /^pull\/.*/
      - deploy-latest-dockerhub:
          context: sceptreorg-dockerhub
          requires:
            - build-docker-image
          filters:
            branches:
              only: master
  tag:
    jobs:
      - build-docker-image:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - deploy-dockerhub-tagged:
          context: sceptreorg-dockerhub
          requires:
            - build-docker-image
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
